### ISSUE TITLE
accessing the server from a private ip

### ISSUE THREAD

**Issue by aSocialMenace** [OpenBazaar/openbazaar-go#1179]
having troube here.. i can consistently set up a openbaraar2.x  server in either the clear net, tor, or dualstack mode on a virtual private server no problem.. But when i try to set up the server on my netwrok the only mode i can get working is the clear net version. I cant get a server on my network to run in tor. Why is this? i uncommented 
#SOCKSPolicy accept 192.168.0.0/16
in my torrc file and configured the ip address range to accept the client i was trying to use. and still noting.. 
First i tried this in a raspberry pi 3 running raspberrian but when that didnt work i threw debian on an old tower i had lying around and installed the server on that.. the same os the vps use and the some settings with the same client yet it dont work. any thoughts guys?

**Comment by aSocialMenace** [comment]
my java console logs have this error

fs.js:652 Uncaught Error: ENOENT: no such file or directory, open '/home/user/openbazaar-desktop/js/templates/modals/TorExternalLinkWarning.html'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
    at loadTemplate (/home/isellcoolshit/openbazaar-desktop/js/utils/loadTemplate.js:18:21)
    at _class.render (/home/user/openbazaar-desktop/js/views/modals/TorExternalLinkWarning.js:49:5)
    at openExternal (/home/user/openbazaar-desktop/js/utils/dom.js:85:8)
    at HTMLAnchorElement.<anonymous> (/home/user/openbazaar-desktop/js/utils/dom.js:120:9)
    at HTMLDocument.dispatch (/home/user/openbazaar-desktop/node_modules/jquery/dist/jquery.js:5183:27)
    at HTMLDocument.elemData.handle (/home/user/openbazaar-desktop/node_modules/jquery/dist/jquery.js:4991:28)

any ideas?

**Comment by drwasho** [comment]
Pinging @cpacia @tyler-smith
