### ISSUE TITLE
multiwallet branch panics on GetByPaymentAddress

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1196]
Not sure exactly the cause or how to reproduce, but I did the following:

- run the server in testnet mode
- send in some TBTC
- send in some TLTC

Observed:
- none of the funds show up. Unconfirmed and confirmed balances remain at 0.
- after starting the server, within a minute it bombs with the following panic:

```
16:45:28.431 [DEBUG] [recordAgingNotifier/PerformTask] notifications created/records updated: purchaseExpire: 0/0, dispute: 0/0, sales: 0/0, purchaseTimeout: 0/0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4958ecb]

goroutine 3785 [running]:
github.com/OpenBazaar/openbazaar-go/repo/db.(*SalesDB).GetByPaymentAddress(0xc4208f3770, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/repo/db/sales.go:239 +0x1ab
github.com/OpenBazaar/openbazaar-go/wallet/listeners.(*TransactionListener).OnTransactionReceived(0xc4209469a0, 0xc420559680, 0x40, 0xc421e1e480, 0x2, 0x2, 0xc421e1e400, 0x1, 0x1, 0xbdec2, ...)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/wallet/listeners/transaction_listener.go:34 +0x145
github.com/OpenBazaar/openbazaar-go/wallet/listeners.(*TransactionListener).OnTransactionReceived-fm(0xc420559680, 0x40, 0xc421e1e480, 0x2, 0x2, 0xc421e1e400, 0x1, 0x1, 0xbdec2, 0x0, ...)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/cmd/start.go:763 +0x65
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).callbackListeners(0xc42051fcb0, 0xc420559680, 0x40, 0xc421e1e480, 0x2, 0x2, 0xc421e1e400, 0x1, 0x1, 0xbdec2, ...)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:504 +0x8f
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).saveSingleTxToDB(0xc42051fcb0, 0xc420559400, 0x40, 0x2, 0xbdebb, 0xc420cf7440, 0x1, 0x4, 0xc420cf7680, 0x2, ...)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:492 +0x1a69
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).saveTxsToDB(0xc42051fcb0, 0xc4213e5400, 0x1, 0x1, 0xc4222f0390)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:373 +0x14c
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).syncTxs(0xc42051fcb0, 0xc4222f0390)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:358 +0x692
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).UpdateState
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:247 +0x2f1
exit status 2
```

**Comment by cpacia** [comment]
I think the issue is the address field coming back from the wallet implementation is nil. I'll need to look into it.
