### ISSUE TITLE
Bug: /ob/estimatetotal triggers a server error [multiwallet]

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1206]
Steps to reproduce:

- Be on the latest commit of the `multiwallet` branch
- Make an `POST /ob/estimatetotal` call with the following payload:

```JSON
{
  "items": [
    {
      "listingHash": "zb2rhaJGKkQkQdPXL84teyCwKG5Mk8ukWRhgfM95fZbwUHRWd",
      "quantity": 1,
      "options": []
    }
  ],
  "moderator": "",
  "paymentCoin": "BCH"
}
```

The server errors with the following:

![image](https://user-images.githubusercontent.com/3887694/46448769-e7708680-c7cb-11e8-9869-1153a9b2339e.png)

The following curl produced this error in a controlled environment:
`curl <target>/ob/estimatefees -d '{"items":[{"listingHash":"zb2rhaJGKkQkQdPXL84teyCwKG5Mk8ukWRhgfM95fZbwUHRWd","quantity":1,"options":[]}],"moderator":"","paymentCoin":"BCH"}'`
```
goroutine 5394796 [running]:
runtime/debug.Stack(0xbec5eb, 0xc4205c1650, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/home/test/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:167 +0x115
panic(0x1223560, 0x20e5e70)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).CreateListing(0xc4207cf700, 0xc42204bba0, 0x174da80, 0xc42204bba0)
	/home/test/go/src/github.com/OpenBazaar/openbazaar-go/core/listings.go:324 +0xa8
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTListing(0xc420121a40, 0x1751340, 0xc4211e4700, 0xc420cca900)
	/home/test/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:521 +0xc5
github.com/OpenBazaar/openbazaar-go/api.post(0xc420121a40, 0xc4298d2210, 0xc, 0x1751340, 0xc4211e4700, 0xc420cca900)
	/home/test/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:28 +0x12b7
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc420121a40, 0x1751340, 0xc4211e4700, 0xc420cca900)
	/home/test/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:176 +0x85d
net/http.(*ServeMux).ServeHTTP(0xc42082fc20, 0x1751340, 0xc4211e4700, 0xc420cca900)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc420824a90, 0x1751340, 0xc4211e4700, 0xc420cca900)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc423748500, 0x1752340, 0xc424229b80)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Comment by placer14** [comment]
@drwasho I was not able to reproduce this state using the latest `multiwallet` branch. 
![screenshot 2018-10-05 10 05 05](https://user-images.githubusercontent.com/305332/46540041-367af200-c886-11e8-9bab-2f196c216d8d.png)

Did you do anything special with your node prior to this? Can you share the config json?

**Comment by drwasho** [comment]
Some more data from a remote node where I replicated the bug:

```
-go/api.(*jsonAPIHandler).ServeHTTP(0xc420121a40, 0x1750800, 0xc42b125880, 0xc42594b500)
        /home/test/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:176 +0x85d
net/http.(*ServeMux).ServeHTTP(0xc4208d1ce0, 0x1750800, 0xc42b125880, 0xc42594b500)
        /usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42084bba0, 0x1750800, 0xc42b125880, 0xc42594b500)
        /usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc426a28dc0, 0x17517c0, 0xc425b78640)
        /usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x27b
goroutine 32246147 [running]:
runtime/debug.Stack(0xbec5eb, 0xc4205c55f0, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
        /home/test/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:167 +0x115
panic(0x1222be0, 0x20e4e70)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).CalculateOrderTotal(0xc420825c00, 0xc425381740, 0x3, 0x1763640, 0xc420859da0)
        /home/test/go/src/github.com/OpenBazaar/openbazaar-go/core/order.go:770 +0x4c
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).Purchase(0xc420825c00, 0xc425381680, 0xc425381680, 0x0, 0x0, 0x0, 0x12f47e0, 0xc42970c6e0, 0x100998de3ec4aca, 0x0)
        /home/test/go/src/github.com/OpenBazaar/openbazaar-go/core/order.go:247 +0x1eca
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTPurchase(0xc420121a40, 0x1750800, 0xc42660a0e0, 0xc422dd5c00)
        /home/test/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:590 +0x12a
github.com/OpenBazaar/openbazaar-go/api.post(0xc420121a40, 0xc42265dfa0, 0xc, 0x1750800, 0xc42660a0e0, 0xc422dd5c00)
        /home/test/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:94 +0x5f4
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc420121a40, 0x1750800, 0xc42660a0e0, 0xc422dd5c00)
        /home/test/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:176 +0x85d
net/http.(*ServeMux).ServeHTTP(0xc4208d1ce0, 0x1750800, 0xc42660a0e0, 0xc422dd5c00)
        /usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42084bba0, 0x1750800, 0xc42660a0e0, 0xc422dd5c00)
        /usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc426a28dc0, 0x17517c0, 0xc425b78640)
        /usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Comment by drwasho** [comment]
Also the API is returning a `200` success response with no value (empty response).

**Comment by placer14** [comment]
FYI, I'm unable to include a newly built framework into the mobile app to test this out with the latest `multiwallet` branch. Please let me know if I need to do anything to get past this error. 
```
Undefined symbols for architecture x86_64:
  "_MobileNewNode", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
```
Restarting xcode was not helpful here. I'm using `make ios_framework` to produce the build and is not creating any error output and exits with a happy `0`. Thoughts?

**Comment by placer14** [comment]
I test both the 1st and 2nd cases on your server after updating to the latest version on `multiwallet`. It no longer panics. I'm exploring how we can better validate inputs but it appears these responses are more reasonable and should no longer block you.
```
[15:58:12] 52 $ curl username:password@45.76.186.204:4002/ob/estimatetotal -d '{"items":[{"listingHash":"zb2rhaJGKkQkQdPXL84teyCwKG5Mk8ukWRhgfM95fZbwUHRWd","quantity":1,"options":[]}],"moderator":"","paymentCoin":"BCH"}'
22294
[multiwallet][mg@io:~/work/ob/openbazaar-go]
[15:59:51] $ curl username:password@45.76.186.204:4002/ob/purchase -d '{"items":[{"listingHash":"zb2rhaJGKkQkQdPXL84teyCwKG5Mk8ukWRhgfM95fZbwUHRWd","quantity":1,"options":[]}],"moderator":"","paymentCoin":"BCH"}'
{
    "success": false,
    "reason": "transaction fee too high for offline 2of2 multisig payment"
}
```

**Comment by drwasho** [comment]
Perfect, thanks guys!
