### ISSUE TITLE
Error when stopping openbazaar-go

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1336]
Using this command, `go run openbazaard.go stop` returned:

```
# command-line-arguments
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x64d236, 0x16)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc024000000, 0x4000000, 0x7fcfd8)
        /usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x7e4560, 0x4000000, 0x0, 0xc000041e30)
        /usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x7e4560, 0x1c6, 0x0)
        /usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x7e4560, 0x1c6, 0x7fcfe8, 0x20300800000000)
        /usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x7e4560, 0x1c6, 0x410101, 0x7f37f5782100)
        /usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x7e4560, 0x1c6, 0xc000000101, 0x415775)
        /usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x38c000, 0x450100, 0x7f37f8d23000)
        /usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc000554830 sp=0xc000554828 pc=0x454b90
runtime.mallocgc(0x38c000, 0x0, 0xc000554900, 0x4b515b)
        /usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc0005548d0 sp=0xc000554830 pc=0x40bb56
runtime.growslice(0x5fe720, 0xc023a8c000, 0x2d5fd2, 0x2d6000, 0x2d601f, 0x0, 0x0, 0xc000056680)
        /usr/local/go/src/runtime/slice.go:197 +0x219 fp=0xc000554938 sp=0xc0005548d0 pc=0x4403c9
cmd/link/internal/ld.putelfstr(0xc00360e9b0, 0x4d, 0x6485fe)
        /usr/local/go/src/cmd/link/internal/ld/symtab.go:51 +0x1ae fp=0xc0005549a8 sp=0xc000554938 pc=0x58d93e
cmd/link/internal/ld.putelfsym(0xc0004d6000, 0xc0035f7410, 0xc00360e9b0, 0x4d, 0x7fcb54, 0x8f4690, 0x0)
        /usr/local/go/src/cmd/link/internal/ld/symtab.go:191 +0x205 fp=0xc000554a58 sp=0xc0005549a8 pc=0x58dd05
cmd/link/internal/ld.genasmsym(0xc0004d6000, 0x657f08)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:2121 +0x802 fp=0xc000554b78 sp=0xc000554a58 pc=0x577822
cmd/link/internal/ld.Asmelfsym(0xc0004d6000)
        /usr/local/go/src/cmd/link/internal/ld/symtab.go:216 +0xd5 fp=0xc000554bc0 sp=0xc000554b78 pc=0x58e4d5
cmd/link/internal/amd64.asmb(0xc0004d6000)
        /usr/local/go/src/cmd/link/internal/amd64/asm.go:774 +0x758 fp=0xc000554ce8 sp=0xc000554bc0 pc=0x59e068
cmd/link/internal/ld.Main(0x7d1c20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x64edf0, 0x1b, 0x64bf34, 0x14, ...)
        /usr/local/go/src/cmd/link/internal/ld/main.go:237 +0xbe2 fp=0xc000554e80 sp=0xc000554ce8 pc=0x583492
main.main()
        /usr/local/go/src/cmd/link/main.go:65 +0x227 fp=0xc000555f98 sp=0xc000554e80 pc=0x5db527
runtime.main()
        /usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000555fe0 sp=0xc000555f98 pc=0x42bae7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000555fe8 sp=0xc000555fe0 pc=0x456af1
```

**Comment by drwasho** [comment]
Another time I ran the same command:

```
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: final link failed: memory exhausted
collect2: error: ld returned 1 exit status

[2]+  Exit 2                  nohup go run openbazaard.go start
```

**Comment by placer14** [comment]
I'm not sure what the `stop` subcommand intended to do but there's nothing implemented that I can see. I'm not surprised it's failing due to invalid memory access, but am surprised that there was no compilation error. Expected the stop implementation to include `Execute` to satisfy the interface requirement.... 

FYI, the daemon is intended to be run synchronously and not in the background with nohup. If you do run it with nohup, you'll need to `kill` it to stop it.

**Comment by placer14** [comment]
Might be worth removing the stop command at least. Will track that in another issue.
