### ISSUE TITLE
/ob/exchangerates panics

### ISSUE THREAD

**Issue by tyler-smith** [OpenBazaar/openbazaar-go#1375]
`curl http://localhost:4002/ob/exchangerates`

```
goroutine 13758 [running]:
runtime/debug.Stack(0xb9c83b, 0xc42061c360, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:162 +0x115
panic(0x137ef20, 0x2349190)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).GETExchangeRate(0xc420473770, 0x18f9580, 0xc4224a0460, 0xc4219d2800)
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:1011 +0x51c
github.com/OpenBazaar/openbazaar-go/api.get(0xc420473770, 0xc422fe6a60, 0x11, 0x18f9580, 0xc4224a0460, 0xc4219d2800)
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:137 +0xfb3
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc420473770, 0x18f9580, 0xc4224a0460, 0xc4219d2800)
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:169 +0x710
net/http.(*ServeMux).ServeHTTP(0xc4208ea210, 0x18f9580, 0xc4224a0460, 0xc4219d2800)
	/usr/local/go/src/net/http/server.go:2340 +0x130
net/http.serverHandler.ServeHTTP(0xc420829ba0, 0x18f9580, 0xc4224a0460, 0xc4219d2800)
	/usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc421700460, 0x18faa00, 0xc420cc5240)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2798 +0x27b
goroutine 13904 [running]:
runtime/debug.Stack(0xb9c83b, 0xc42061c360, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:162 +0x115
panic(0x137ef20, 0x2349190)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).GETExchangeRate(0xc420473770, 0x18f9580, 0xc4218a6540, 0xc420642600)
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:1011 +0x51c
github.com/OpenBazaar/openbazaar-go/api.get(0xc420473770, 0xc4220fc040, 0x11, 0x18f9580, 0xc4218a6540, 0xc420642600)
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:137 +0xfb3
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc420473770, 0x18f9580, 0xc4218a6540, 0xc420642600)
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:169 +0x710
net/http.(*ServeMux).ServeHTTP(0xc4208ea210, 0x18f9580, 0xc4218a6540, 0xc420642600)
	/usr/local/go/src/net/http/server.go:2340 +0x130
net/http.serverHandler.ServeHTTP(0xc420829ba0, 0x18f9580, 0xc4218a6540, 0xc420642600)
	/usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc42179a3c0, 0x18faa00, 0xc423530700)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2798 +0x27b

```

**Comment by jjeffryes** [comment]
@tyler-smith have you seen this recently? I haven't been able to reproduce it.

**Comment by cpacia** [comment]
I think this is fixed. Wasn't initialized properly.
