### ISSUE TITLE
Panic when shutting down wallet

### ISSUE THREAD

**Issue by tyler-smith** [OpenBazaar/openbazaar-go#1376]
Happens to me about 1/3 of the time when shutting down.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xcf80d5]

goroutine 377 [running]:
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook.(*wsWatchdog).guardWebsocket(0xc4205e5140)
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go:54 +0x1e5
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook.(*BlockBookClient).setupListeners
	/home/tyler/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go:545 +0x232
exit status 2
```

**Comment by jjeffryes** [comment]
@tyler-smith @placer14 @cpacia was this fixed? I don't think I've seen it recently.

**Comment by cpacia** [comment]
I think this is fixed
