### ISSUE TITLE
Crash on re-broadcasting transaction

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#1388]
When a new block comes in it will try to re-broadcast transactions which have zero confirmations. This sometimes results in a panic when the broadcast API call returns an error.

```
goroutine 113579 [running]:
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client.(*healthState).nextAvailable(0x0, 0x227c8f5013f, 0x27f09c0, 0xc0040c9ba0)
	/home/chris/workspace/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/rotation_manager.go:40 +0x22
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client.(*healthState).markUnhealthy(0x0)
	/home/chris/workspace/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/rotation_manager.go:20 +0x51
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client.(*rotationManager).FailCurrent(0xc0011b5440)
	/home/chris/workspace/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/rotation_manager.go:146 +0x9a
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client.(*ClientPool).FailAndCloseCurrentClient(0xc0004de780)
	/home/chris/workspace/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/pool.go:127 +0x38
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client.(*ClientPool).executeRequest(0xc0004de780, 0xc001b23b00, 0x20, 0xc0016976c0)
	/home/chris/workspace/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/pool.go:161 +0x99
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client.(*ClientPool).Broadcast(0xc0004de780, 0xc0019b8480, 0x207, 0x207, 0xc0016976c0, 0x40, 0x8c33fc, 0xc003922e40)
	/home/chris/workspace/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/pool.go:189 +0x9a
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).processIncomingBlock.func1(0xc001199710, 0xc002c3e1c0, 0xc0027901b0, 0xc0019bc000, 0xd, 0x10, 0xc00131fd80, 0xc001a1e780, 0x40, 0x0, ...)
	/home/chris/workspace/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:228 +0x25d
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service.(*WalletService).processIncomingBlock
	/home/chris/workspace/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:208 +0x959
exit status 2
```

**Comment by placer14** [comment]
Here's a new instance of the same issue:
```
15:37:01.690 [DEBUG] [WalletService/syncUtxos] Downloaded 8 Bitcoin utxos
15:37:01.833 [DEBUG] [WalletService/syncTxs] Downloaded 22 Bitcoin transactions
15:37:02.234 [INFO] [pool/executeRequest] error executing wallet client request: error broadcasting tx: status not ok: 400 Bad Request
15:37:02.234 [INFO] [client/Close] closing client (btc.blockbook.api.openbazaar.org)...
15:37:02.235 [WARNING] [client/func2] websocket disconnected: btc.blockbook.api.openbazaar.org
15:37:04.851 [INFO] [client/setupListeners] Connected to websocket endpoint btc.blockbook.api.openbazaar.org
15:37:05.752 [INFO] [pool/executeRequest] error executing wallet client request: error broadcasting tx: status not ok: 400 Bad Request
15:37:05.752 [INFO] [client/Close] closing client (btc.blockbook.api.openbazaar.org)...
15:37:05.752 [WARNING] [client/func2] websocket disconnected: btc.blockbook.api.openbazaar.org
15:37:05.858 [WARNING] [client/guardWebsocket] reconnecting stopped websocket (btc.blockbook.api.openbazaar.org)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4938fc4]

goroutine 379461 [running]:
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook.(*wsWatchdog).guardWebsocket(0xc0012588c0)
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go:55 +0x254
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook.(*BlockBookClient).setupListeners
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go:549 +0x187
exit status 2
```
```
15:33:08.270 [DEBUG] [WalletService/UpdateState] Litecoin chain height: 1559799
15:33:08.281 [DEBUG] [WalletService/syncTxs] Querying for Litecoin transactions
15:33:08.282 [DEBUG] [WalletService/syncUtxos] Querying for Litecoin utxos
15:33:09.063 [INFO] [pool/executeRequest] error executing wallet client request: Get https://ltc.blockbook.api.openbazaar.org/api/address/LTyDZbsGhW2HVtDRLC9mGnMHn4EZC13gi9?%3Fpage=1: read tcp 192.168.1.187:63868->138.68.199.152:443: read: connection reset by peer
15:33:09.098 [INFO] [pool/executeRequest] error executing wallet client request: Get https://ltc.blockbook.api.openbazaar.org/api/utxo/LaKvetC9GxaYLuxaSvg3FxCWeA66Kb2bz4: read tcp 192.168.1.187:63968->138.68.199.152:443: read: connection reset by peer
15:33:09.098 [INFO] [client/Close] closing client (ltc.blockbook.api.openbazaar.org)...
15:33:09.098 [WARNING] [client/func2] websocket disconnected: ltc.blockbook.api.openbazaar.org
15:33:09.098 [WARNING] [client/guardWebsocket] reconnecting stopped websocket (ltc.blockbook.api.openbazaar.org)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4938fc4]

goroutine 74243 [running]:
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook.(*wsWatchdog).guardWebsocket(0xc00127f540)
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go:55 +0x254
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook.(*BlockBookClient).setupListeners
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go:549 +0x187
exit status 2
```

**Comment by placer14** [comment]
Should be fixed by https://github.com/OpenBazaar/openbazaar-go/pull/1391
