### ISSUE TITLE
Can't Make Offline Purchase

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1451]
When making a purchase from an offline 2.3 node, a node using the IPFS refactor branch returns a status of 200 OK from the ob/purchase call, but returns no data.

**Comment by jjeffryes** [comment]
I haven't been able to replicate this since the first time it happened. It may be something that needs some hard to replicate set of circumstances to happen.

**Comment by jjeffryes** [comment]
I've replicated it on a second buying node.

**Comment by jjeffryes** [comment]
In both cases, this happened on the first buying attempt between an IPFS rebase node and a 2.3 offline node. I don't know if that's the critical element that causes this to happen.

**Comment by jjeffryes** [comment]
This appears to be working with the IPFS migration branch.

**Comment by jjeffryes** [comment]
I've had this happen now with two 2.3.1 nodes trying to buy from each other.

**Comment by jjeffryes** [comment]
```
goroutine 12316 [running]:
runtime/debug.Stack(0x49cdf3b, 0xc0007be2d0, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:167 +0x10b
panic(0x52a34e0, 0x6803240)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).SendOrder(0xc000de0ea0, 0xc001ff46c0, 0x2e, 0xc00356e480, 0x0, 0x0, 0x0)
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/core/net.go:279 +0x19d
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).Purchase(0xc000de0ea0, 0xc00356e300, 0xc00356e300, 0x0, 0x0, 0x203000, 0xc0017d39a8, 0x400e53f, 0x400e53f, 0xc0017d3950)
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/core/order.go:106 +0x181
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTPurchase(0xc000ffe500, 0x594f3e0, 0xc000f749a0, 0xc002ea5f00)
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:590 +0x125
github.com/OpenBazaar/openbazaar-go/api.post(0xc000ffe500, 0xc000deb1d0, 0xc, 0x594f3e0, 0xc000f749a0, 0xc002ea5f00)
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:101 +0x752
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc000ffe500, 0x594f3e0, 0xc000f749a0, 0xc002ea5f00)
	/Users/jjeffryes/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:176 +0x829
net/http.(*ServeMux).ServeHTTP(0xc000e00c60, 0x594f3e0, 0xc000f749a0, 0xc002ea5f00)
	/usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000e2e5b0, 0x594f3e0, 0xc000f749a0, 0xc002ea5f00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000930140, 0x5950fe0, 0xc000b85f00)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by jjeffryes** [comment]
Once this happens, the node can't complete any purchase calls from any other node, online or offline.
