### ISSUE TITLE
PATCH ob/profile crashes

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1700]
This happen on the `wallet-resp` branch.

```
goroutine 54528 [running]:
runtime/debug.Stack(0x49dfc8b, 0xc000729620, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:176 +0x10b
panic(0x52c2ae0, 0x6862d30)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/OpenBazaar/openbazaar-go/core.ValidateProfile(0xc000106e10, 0xc001d0f200, 0x0)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/core/profile.go:334 +0x348
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).UpdateProfile(0xc0009706c0, 0xc000106e10, 0x0, 0x0)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/core/profile.go:69 +0x86
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).PatchProfile(0xc0009706c0, 0xc0016b5d70, 0xc0023dbb00, 0x0)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/core/profile.go:179 +0x44c
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).PATCHProfile(0xc00112c800, 0x597f9a0, 0xc00044ea80, 0xc002029800)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:390 +0x1d4
github.com/OpenBazaar/openbazaar-go/api.patch(0xc00112c800, 0xc0028d6100, 0x3a, 0x597f9a0, 0xc00044ea80, 0xc002029800)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:222 +0x72
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc00112c800, 0x597f9a0, 0xc00044ea80, 0xc002029800)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:191 +0x855
net/http.(*ServeMux).ServeHTTP(0xc000960d80, 0x597f9a0, 0xc00044ea80, 0xc002029800)
	/usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0008ffa00, 0x597f9a0, 0xc00044ea80, 0xc002029800)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00265ab40, 0x5981560, 0xc0013e5e80)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

This is the input I'm sending:

```
{
  "moderator": true,
  "moderatorInfo": {
    "fee": {
      "feeType": "FIXED",
      "fixedFee": {
        "currencyCode": "USD"
      },
      "percentage": 0
    },
    "description": "howdy",
    "termsAndConditions": "slater",
    "languages": [
      "en-US"
    ]
  }
}
```

I realize I'm likely sending wrong data, but IMHO the server still shouldn't crash and ideally would return a message indicating which data is not to its liking.

**Comment by drwasho** [comment]
On the `update-listing` branch, based off of `ethereum-master`, this bug isn't happening. It's fixed in `ethereum-master` or it will be fixed when PR #1728 is merged... either way, safe to close for now.
