### ISSUE TITLE
PATCH settings cause a panic

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1821]
I PATCH `ob/settings` with the following data:

```
{
  "storeModerators": ["QmeRfQcEiefLYgEFRsNqn1WjjrLjrJVAddt85htU1Up32y"]
}
```

The response code is `200`, but the response is empty (which is invalid JSON).

And the data provided is not persisted in the users settings. And the server panics:

```
: 00000000000000000001dcf68773bcd43b8f823f54b2ce456d02683801d39daa
goroutine 2060 [running]:
runtime/debug.Stack(0x49e851b, 0xc00038a6c0, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:177 +0x10b
panic(0x5348700, 0x697eee0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).SetModeratorsOnListings.func1(0xc0029a13b0, 0x48, 0x5a37fc0, 0xc002f2c410, 0x0, 0x0, 0xc, 0xc002739668)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/core/moderation.go:261 +0x372
path/filepath.walk(0xc0029a13b0, 0x48, 0x5a37fc0, 0xc002f2c410, 0xc004855d40, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:358 +0x41c
path/filepath.walk(0xc001e14e80, 0x3b, 0x5a37fc0, 0xc002f2c340, 0xc004855d40, 0x0, 0x30)
	/usr/local/go/src/path/filepath/path.go:382 +0x2fe
path/filepath.Walk(0xc001e14e80, 0x3b, 0xc004855d40, 0x3b, 0x0)
	/usr/local/go/src/path/filepath/path.go:404 +0x105
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).SetModeratorsOnListings(0xc0011dcc60, 0x6b6e148, 0x0, 0x0, 0x0, 0x0)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/core/moderation.go:302 +0x15e
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).PATCHSettings(0xc0012e2a00, 0x5a2d1a0, 0xc000a4c8c0, 0xc0012e3400)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:1055 +0x781
github.com/OpenBazaar/openbazaar-go/api.patch(0xc0012e2a00, 0xc000cf0c10, 0xd, 0x5a2d1a0, 0xc000a4c8c0, 0xc0012e3400)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:220 +0x10d
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc0012e2a00, 0x5a2d1a0, 0xc000a4c8c0, 0xc0012e3400)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:192 +0x855
net/http.(*ServeMux).ServeHTTP(0xc0009b43c0, 0x5a2d1a0, 0xc000a4c8c0, 0xc0012e3400)
	/usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc00098e820, 0x5a2d1a0, 0xc000a4c8c0, 0xc0012e3400)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc001f446e0, 0x5a2ed60, 0xc0013d1a80)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

*Expectations:*

- The data is persisted if it's valid and valid JSON is returned otherwise a `500` error is returned with a reason.
- No panic

**Comment by rmisio** [comment]
If you need the users profile or settings, please let me know.

**Comment by rmisio** [comment]
FWIW, the same thing happens if I `PUT` the settings with the full data set.
