### ISSUE TITLE
Panic on PATCH /ob/settings specific to store moderators

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1866]
Found the following panic when sending the following payload to `PATCH /ob/settings`:
```
{"storeModerators":[]}
```

Panic:
```
goroutine 2693 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/runtime/debug/stack.go:24 +0xb1
runtime/debug.PrintStack()
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:177 +0x16c
panic(0x5ad53a0, 0x73f5f70)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/runtime/panic.go:513 +0x1e6
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).SetModeratorsOnListings.func1(0xc001fa4d20, 0x98, 0x637eec0, 0xc00299ef70, 0x0, 0x0, 0x0, 0x0)
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/core/moderation.go:261 +0x63c
path/filepath.walk(0xc001fa4d20, 0x98, 0x637eec0, 0xc00299ef70, 0xc0025f3ce0, 0x0, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/path/filepath/path.go:358 +0x6af
path/filepath.walk(0xc0005d87e0, 0x81, 0x637eec0, 0xc00299eea0, 0xc0025f3ce0, 0x0, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/path/filepath/path.go:382 +0x581
path/filepath.Walk(0xc0005d87e0, 0x81, 0xc0025f3ce0, 0x0, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/path/filepath/path.go:404 +0x1e5
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).SetModeratorsOnListings(0xc0005e7d40, 0x75e51e8, 0x0, 0x0, 0x0, 0x0)
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/core/moderation.go:302 +0x2bf
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).PATCHSettings(0xc0013fc100, 0x63742e0, 0xc00117e1c0, 0xc00016db00)
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:1055 +0x817
github.com/OpenBazaar/openbazaar-go/api.patch(0xc0013fc100, 0xc00193f320, 0xd, 0x63742e0, 0xc00117e1c0, 0xc00016db00)        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:220 +0x8b
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc0013fc100, 0x63742e0, 0xc00117e1c0, 0xc00016db00)
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:192 +0x14e3
net/http.(*ServeMux).ServeHTTP(0xc0014c7a40, 0x63742e0, 0xc00117e1c0, 0xc00016db00)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/net/http/server.go:2361 +0x1a4
net/http.serverHandler.ServeHTTP(0xc0000ff450, 0x63742e0, 0xc00117e1c0, 0xc00016db00)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/net/http/server.go:2741 +0x1e9
net/http.(*conn).serve(0xc000a5f0e0, 0x6375ee0, 0xc0011ba880)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/net/http/server.go:1847 +0x1146
created by net/http.(*Server).Serve
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/net/http/server.go:2851 +0x7b0
```

**Comment by drwasho** [comment]
That's the one!

**Comment by placer14** [comment]
I no longer seem to be able to reproduce this bug. Either the underlying data initialization was improved or my node state has changed away from the logic path which triggered this. It could've also been due to bad migrations which no longer create the data to cause this. I'm going to do some more testing and tighten up the path where the bug was last seen at least. 

@drwasho I don't know if you still have a scenario which produces this bug, but could you check?

**Comment by drwasho** [comment]
Ugh, the bug I thought I was seeing was because I was using (`moderators`) was incorrect; it should have been `storeModerators`.

Not sure when this changed, if it wasn't this all along, but I've updated the API documentation.

**Comment by drwasho** [comment]
Closing this as it doesn't seem to be an issue anymore; if I forgot that we wanted to keep this open, please reopen.
