### ISSUE TITLE
'Send all' feature in wallet exposes an error

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1907]
The problem is caused by a branch made by @hoffmabc that we merged into the `mobileFixesStdout` branch to fix https://github.com/OpenBazaar/openbazaar-go/pull/1729:

![image](https://user-images.githubusercontent.com/3887694/70207331-31f5e600-1776-11ea-8ce6-d6a2cc020ee9.png)

The error produced when `spendAll` was set to `true`:

```
goroutine 12033 [running]:
runtime/debug.Stack(0x49e72eb, 0xc00057c660, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:169 +0x10b
panic(0x52f9f80, 0x68b7b90)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).Spend(0xc0006db0e0, 0xc000abf280, 0xc000abf280, 0x0, 0x0)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/core/spend.go:127 +0x889
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTSpendCoins(0xc001193400, 0x59bc080, 0xc000456380, 0xc0004ff000)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:795 +0x11d
github.com/OpenBazaar/openbazaar-go/api.post(0xc001193400, 0xc001734e00, 0xd, 0x59bc080, 0xc000456380, 0xc0004ff000)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:39 +0x1853
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc001193400, 0x59bc080, 0xc000456380, 0xc0004ff000)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:178 +0x8a3
net/http.(*ServeMux).ServeHTTP(0xc0005e24e0, 0x59bc080, 0xc000456380, 0xc0004ff000)
        /usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000964000, 0x59bc080, 0xc000456380, 0xc0004ff000)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc001276b40, 0x59bdcc0, 0xc001918540)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

We should:

- [ ] 1. Consider fixing this problem so that it doesn't cause issues when trying to spend the wallet balance, since the network message we're sending to notify a peer that a payment for an order was made is supposed to help peers detect order-related payments (and this network message is being used today by all of our nodes)
- [ ] 2. Make sure this problem isn't happening on `ethereum-master`

It also isn't clear whether this is at all related to the order reliability issues reported by our users.

**Comment by hoffmabc** [comment]
This bug is not present in ethereum-master because there's a nil check for it. I can add to the patch for master @drwasho
