### ISSUE TITLE
Bug: POST /ob/purchase API call is failing when purchasing a moderated listing

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1977]
The body payload:

```JSON
{
    "shipTo": "Elwood Blues",
    "address": "1060 W Addison",
    "city": "Chicago",
    "state": "Illinois",
    "countryCode": "UNITED_STATES",
    "postalCode": "60613",
    "addressNotes": "",
    "items": [
        {
            "listingHash": "Qmc9WBrkf7HGTfgNe1tVdGt6CgAMSJkQu2aN3Yr3nt52fu",
            "bigQuantity": "1",
            "options": [
                {
                    "name": "Sizes",
                    "value": "Small"
                },
                {
                    "name": "Color",
                    "value": "Red"
                }
            ],
            "shipping": {
                "name": "Worldwide",
                "service": "Standard"
            },
            "memo": "thanks!",
            "coupons": []
        }
    ],
    "moderator": "QmcdkKM2fWCKzTZdpjEY6abzRbDhRRJvNmqwNKVyiDtGky",
    "paymentCoin": "TETH"
}
```

The listing can be found [here](https://gist.github.com/drwasho/f812adca264d985339bcc041d0ec3faf).

The STDOUT dump:

```
2020-02-06 08:59:02.403 [ERROR] [core/CalculateOrderTotal] Currency not tracked
goroutine 16702 [running]:
runtime/debug.Stack(0x4a3b57b, 0xc0007cc3c0, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:176 +0x10b
panic(0x53353c0, 0x692bf10)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
math/big.(*Int).Cmp(0x0, 0xc000b99ac0, 0x0)
        /usr/local/go/src/math/big/int.go:319 +0x26
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).CalculateOrderTotal(0xc0007ea120, 0xc0027c9200, 0x4, 0xc000c01220, 0x5)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/core/order.go:1026 +0x1119
github.com/OpenBazaar/openbazaar-go/core.prepareModeratedOrderContract(0xc0027c9140, 0xc0007ea120, 0xc0027c9200, 0x5a25d40, 0xc000a6c4d0, 0x0, 0x0, 0x8)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/core/order.go:226 +0x592
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).Purchase(0xc0007ea120, 0xc0027c9140, 0xc0027c9140, 0x0, 0x0, 0x10, 0x200, 0x80, 0x7f, 0xc001315948)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/core/order.go:125 +0x237
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTPurchase(0xc00047de00, 0x5a0b0e0, 0xc000d061c0, 0xc001898c00)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:594 +0x125
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTPurchase-fm(0x5a0b0e0, 0xc000d061c0, 0xc001898c00)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:101 +0x48
github.com/OpenBazaar/openbazaar-go/api.blockingStartupMiddleware(0xc00047de00, 0x5a0b0e0, 0xc000d061c0, 0xc001898c00, 0xc0013159f8)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:270 +0x62
github.com/OpenBazaar/openbazaar-go/api.post(0xc00047de00, 0xc00181a7f0, 0xc, 0x5a0b0e0, 0xc000d061c0, 0xc001898c00)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:101 +0x7fe
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc00047de00, 0x5a0b0e0, 0xc000d061c0, 0xc001898c00)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:185 +0x8a3
net/http.(*ServeMux).ServeHTTP(0xc00144aa20, 0x5a0b0e0, 0xc000d061c0, 0xc001898c00)
        /usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc00068f790, 0x5a0b0e0, 0xc000d061c0, 0xc001898c00)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000ce1680, 0x5a0cbe0, 0xc002653740)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by drwasho** [comment]
This panic isn't occurring anymore.
