### ISSUE TITLE
Bug: Panic in the moderator's node when attempting to close a dispute

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1978]
This showed up during testing. The order itself had problems that would cause this API to error, but I'm guess it shouldn't panic:

```
goroutine 24586 [running]:
runtime/debug.Stack(0x4a3b57b, 0xc0002e42d0, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:176 +0x10b
panic(0x53353c0, 0x692bf10)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTCloseDispute(0xc000b70800, 0x5a0b0e0, 0xc003a0c540, 0xc001c02400)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:2156 +0x163
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTCloseDispute-fm(0x5a0b0e0, 0xc003a0c540, 0xc001c02400)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:67 +0x48
github.com/OpenBazaar/openbazaar-go/api.blockingStartupMiddleware(0xc000b70800, 0x5a0b0e0, 0xc003a0c540, 0xc001c02400, 0xc002283a58)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:270 +0x62
github.com/OpenBazaar/openbazaar-go/api.post(0xc000b70800, 0xc001c6c4a0, 0x10, 0x5a0b0e0, 0xc003a0c540, 0xc001c02400)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:67 +0x10a4
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc000b70800, 0x5a0b0e0, 0xc003a0c540, 0xc001c02400)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:185 +0x8a3
net/http.(*ServeMux).ServeHTTP(0xc001639ef0, 0x5a0b0e0, 0xc003a0c540, 0xc001c02400)
        /usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc001903110, 0x5a0b0e0, 0xc003a0c540, 0xc001c02400)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0031500a0, 0x5a0cbe0, 0xc002868fc0)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by drwasho** [comment]
I think this panic has been resolved; closing for now.
