### ISSUE TITLE
Bug: Panic when attempting to POST /ob/ordercomplete

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1999]
The order had some issues, but the server panicked when this API call was made:

```
2020-02-24 14:45:12.545 [DEBUG] [recordAgingNotifier/PerformTask] notifications created/records updated: sales: 0/0, purchaseTimeout: 0/0, purchaseExpire: 0/0, dispute: 0/0
goroutine 78308 [running]:
runtime/debug.Stack(0x4a3b03b, 0xc000337830, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:176 +0x10b
panic(0x5338780, 0x6932f10)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).CompleteOrder(0xc000f127e0, 0xc001b26db0, 0xc000a40480, 0xc003cf1780, 0x2, 0x4, 0x4, 0x8)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/core/completion.go:115 +0x1eb5
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTOrderComplete(0xc000da4300, 0x5a0f520, 0xc000e3cb60, 0xc00262e600)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:2076 +0x474
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTOrderComplete-fm(0x5a0f520, 0xc000e3cb60, 0xc00262e600)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:55 +0x48
github.com/OpenBazaar/openbazaar-go/api.blockingStartupMiddleware(0xc000da4300, 0x5a0f520, 0xc000e3cb60, 0xc00262e600, 0xc001983a98)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:270 +0x62
github.com/OpenBazaar/openbazaar-go/api.post(0xc000da4300, 0xc000b1df40, 0x13, 0x5a0f520, 0xc000e3cb60, 0xc00262e600)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:55 +0x141e
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc000da4300, 0x5a0f520, 0xc000e3cb60, 0xc00262e600)
        /Users/drwasho/Work/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:185 +0x8a3
net/http.(*ServeMux).ServeHTTP(0xc001773ef0, 0x5a0f520, 0xc000e3cb60, 0xc00262e600)
        /usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0008b2340, 0x5a0f520, 0xc000e3cb60, 0xc00262e600)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc001acde00, 0x5a11020, 0xc000897b00)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by drwasho** [comment]
I've made this call several times now and haven't seen the problem. I'm tentatively closing this and will reopen if I see the problem again.
