### ISSUE TITLE
Send on closed channel [SPV Wallet]

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-go#333]
Go server crashes.

```
12:00:58.225 [ServeHTTP] [DEBUG] GET /ob/followers HTTP/1.1
Host: localhost:4002
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Connection: keep-alive
Cookie: io=mYYOuKoITlAld7IpAAAB
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) openbazaar-desktop/2.0.0 Chrome/53.0.2785.143 Electron/1.4.14 Safari/537.36

panic: send on closed channel

goroutine 61413 [running]:
panic(0x4d65300, 0xc82415e5f0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:464 +0x3e6
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).onInv.func1(0xc82501a760, 0xc822740840, 0xc821fd3130)
	/Users/brianhoffman/golang/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/eight333.go:110 +0x3b0
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).onInv
	/Users/brianhoffman/golang/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/eight333.go:121 +0x49
exit status 2
```

**Comment by cpacia** [comment]
This is fixed in master

**Comment by hoffmabc** [comment]
I am seeing this in master.

**Comment by cpacia** [comment]
Fixed for now. Still could probably use some refactoring or at least to figure out why it was calling on a closed channel to begin with.
