### ISSUE TITLE
Server is crashing after attempting to send chat messages between two nodes.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#364]
After attempting to send some chat messages back and forth between two nodes, the server is crashing:

```
09:06:35.597 [SendMessage] [DEBUG] Sending OFFLINE_ACK message to Qma8M2EfQ5mWeoafuGmRqqPa2DMzshB9y9wTYNRUVdyAts
09:06:35.597 [SendOfflineMessage] [DEBUG] Sending offline message to Qma8M2EfQ5mWeoafuGmRqqPa2DMzshB9y9wTYNRUVdyAts
09:06:45.686 [handleChat] [DEBUG] Received CHAT message from Qma8M2EfQ5mWeoafuGmRqqPa2DMzshB9y9wTYNRUVdyAts
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4218cbd]

goroutine 1045 [running]:
panic(0x4c62b80, 0xc42000e0a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/OpenBazaar/openbazaar-go/net/service.(*OpenBazaarService).handleChat(0xc420094fa0, 0xc421c8f0b0, 0x22, 0xc421c1cb80, 0x4be5bc0, 0xc4214e4868, 0x4be5bc0, 0xc4214e4868, 0xc4204b9d27)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/net/service/handlers.go:928 +0x27d
github.com/OpenBazaar/openbazaar-go/net/service.(*OpenBazaarService).(github.com/OpenBazaar/openbazaar-go/net/service.handleChat)-fm(0xc421c8f0b0, 0x22, 0xc421c1cb80, 0x4be5bc0, 0xc4214e4868, 0x30, 0x2e, 0xc421ca8360)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/net/service/handlers.go:58 +0x5c
github.com/OpenBazaar/openbazaar-go/net/retriever.(*MessageRetriever).handleMessage(0xc4200950e0, 0xc421c1cb80, 0xc421c8eff0, 0x24, 0x24, 0xc4212ffc00, 0x40, 0x40, 0xc4204b9e28)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/net/retriever/retriever.go:214 +0xf6
github.com/OpenBazaar/openbazaar-go/net/retriever.(*MessageRetriever).attemptDecrypt(0xc4200950e0, 0xc4206aad20, 0xe7, 0xe7, 0xc4212ad590, 0x22)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/net/retriever/retriever.go:189 +0x484
github.com/OpenBazaar/openbazaar-go/net/retriever.(*MessageRetriever).fetchIPFS(0xc4200950e0, 0xc4212ad590, 0x22, 0x1, 0xc4201d7c00, 0x34, 0x0, 0x0, 0xc420674640, 0x0, ...)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/net/retriever/retriever.go:120 +0x201
created by github.com/OpenBazaar/openbazaar-go/net/retriever.(*MessageRetriever).fetchPointers
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/net/retriever/retriever.go:73 +0x859
exit status 2
```

**Comment by rmisio** [comment]
Also, getting this:

```
09:33:50.085 [ServeHTTP] [DEBUG] GET /ob/chatconversations HTTP/1.1
Host: localhost:4002
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Connection: keep-alive
Cookie: io=C8GZF2Y3g1huos0iAAAA
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) openbazaar-desktop/2.0.0 Chrome/53.0.2785.143 Electron/1.4.12 Safari/537.36

panic: close of closed channel

goroutine 3400 [running]:
panic(0x4c62c40, 0xc42183c240)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).startChainDownload(0xc420628370, 0xc4200ed340)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/eight333.go:30 +0x18f
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).(github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.startChainDownload)-fm(0xc4200ed340)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/wallet.go:122 +0x34
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*PeerManager).setDownloadPeer
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/peers.go:275 +0x11f
exit status 2
```

**Comment by drwasho** [comment]
This can be closed, but the db needed to be blown away. To avoid issues like these again, I suggest the following: https://github.com/OpenBazaar/openbazaar-go/issues/365

**Comment by rmisio** [comment]
Just for the record, these issue weren't happening because the DB needed to be blown away. They did also require some new commits (e.g. https://github.com/OpenBazaar/openbazaar-go/commit/ac48cd9ba2115f364d520238108dc895388882bf). One of those new commits then required you to blow away your DB.

So, blowing away the DB was just one piece to the puzzle.

**Comment by rmisio** [comment]
In either case though, this bug does look to be fixed.
