### ISSUE TITLE
Panic when working with wallet API

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#423]
I was playing with the wallet API and got a panic. Can't immediately reproduce but will update if I can get a reduced test case.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45c52e2]

goroutine 11947 [running]:
panic(0x4c7e6c0, 0xc42000e0a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer.(*Peer).ID(0x0, 0xb)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer/peer.go:524 +0x22
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).onMerkleBlock(0xc42028f8c0, 0xc4216d3080, 0xc4219e7680)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/eight333.go:46 +0x65
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).(github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.onMerkleBlock)-fm(0xc4216d3080, 0xc4219e7680)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/wallet.go:97 +0x3e
github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer.(*Peer).inHandler(0xc4216d3080)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer/peer.go:1564 +0xbc4
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer.(*Peer).start
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer/peer.go:1965 +0x2b5
exit status 2
```

**Comment by JustinDrake** [comment]
My guess is that it's related to `/wallet/resyncblockchain`.

**Comment by cpacia** [comment]
This api call appears to be working fine now.
