### ISSUE TITLE
Panic on bootup

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#427]
It seems I've got my node in a bad state. It now always panics on bootup

```
OpenBazaar Server v0.5.1 starting...
13:00:02.068 [Execute] [INFO] Peer ID:  QmNVdnnhKX1Dkt3iLYaGwEMEQ9fXVFZhWv9STJCt9RCZBz
13:00:02.070 [printSwarmAddrs] [INFO] Swarm listening on /ip4/127.0.0.1/tcp/4001
13:00:02.070 [printSwarmAddrs] [INFO] Swarm listening on /ip4/127.0.0.1/tcp/9005/ws
13:00:02.071 [printSwarmAddrs] [INFO] Swarm listening on /ip4/192.168.92.243/tcp/4001
13:00:02.071 [printSwarmAddrs] [INFO] Swarm listening on /ip4/192.168.92.243/tcp/9005/ws
13:00:02.071 [printSwarmAddrs] [INFO] Swarm listening on /ip6/::1/tcp/4001
13:00:02.071 [printSwarmAddrs] [INFO] Swarm listening on /ip6/::1/tcp/9005/ws
13:00:02.128 [newHTTPGateway] [INFO] Gateway/API server listening on /ip4/127.0.0.1/tcp/4002
13:00:02.129 [New] [INFO] OpenBazaar service running at /openbazaar/app/1.0.0
13:00:12.230 [func4] [INFO] Starting bitcoin wallet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41c23f0]

goroutine 308 [running]:
panic(0x4c7e6c0, 0xc42000e0a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/OpenBazaar/openbazaar-go/api.(*notificationManager).getNotifiers(0xc420078210, 0x4324739, 0xc4201cdf28, 0x40133f5)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/api/notifier.go:61 +0x100
github.com/OpenBazaar/openbazaar-go/api.(*notificationManager).sendNotification(0xc420078210, 0x4ca2400, 0xc4217382b0)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/api/notifier.go:43 +0x2f
github.com/OpenBazaar/openbazaar-go/api.manageNotifications.func1(0xc42009f080, 0xc420078210, 0xc42009ef00)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/api/notifier.go:30 +0x83
created by github.com/OpenBazaar/openbazaar-go/api.manageNotifications
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/api/notifier.go:33 +0xa3
exit status 2
```

**Comment by tyler-smith** [comment]
Clear your db until we have data migrations.

**Comment by JustinDrake** [comment]
@tyler-smith I guess I didn't explain that I started with a fresh DB, played with the API, and then got into this bad state.

**Comment by tyler-smith** [comment]
Gotcha. Not good obviously. Back up that data directory. Please try and figure out what's wrong with its state if you can but if not, and it happens again, me or @cpacia can try checking out the backed up data to see if we can find the issue.
