### ISSUE TITLE
Index out of range with POST /ob/purchase

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#429]
POST /ob/purchase {} will panic with index out of range

```
13:08:22.707 [ServeHTTP] [DEBUG] POST /ob/purchase HTTP/1.1
Host: localhost:4002
Connection: close
Connection: close
Content-Length: 2
Content-Type: application/json

13:08:23.640 [func1] [ERROR] A panic occurred in the rest api handler!
13:08:23.640 [func1] [ERROR] runtime error: index out of range
goroutine 773 [running]:
runtime/debug.Stack(0x42d874b, 0xc4201b80f0, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:129 +0x150
panic(0x4c7e6c0, 0xc42000e0e0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).Purchase(0xc420107440, 0xc421422dc0, 0xc421422dc0, 0x0, 0x0, 0x0, 0xc42158df10, 0xc42158df10, 0xc420725980, 0x4051391)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/core/order.go:401 +0x48ec
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTPurchase(0xc420dd9770, 0x558a680, 0xc4214f5ba0, 0xc4215b4000)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:624 +0x156
github.com/OpenBazaar/openbazaar-go/api.post(0xc420dd9770, 0xc42158df10, 0xc, 0x558a680, 0xc4214f5ba0, 0xc4215b4000)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:28 +0xc2a
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc420dd9770, 0x558a680, 0xc4214f5ba0, 0xc4215b4000)
	/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:142 +0x8e8
net/http.(*ServeMux).ServeHTTP(0xc42060c540, 0x558a680, 0xc4214f5ba0, 0xc4215b4000)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc4203cd780, 0x558a680, 0xc4214f5ba0, 0xc4215b4000)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42159a580, 0x558b680, 0xc421445cc0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by tyler-smith** [comment]
I think it would be more productive to compress most of these api panicking issues into something like "API needs to better fault tolerance and error codes/messages".

- We should catch panics (which should never happen, but if they do shouldn't kill everything)
- Log if a panic happens
- Be consistent with HTTP response status codes and messages
- Have a mode/flag that _does_ die on panics for devs so we can more easily find and fix them
