### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#47]
Trying to get `openbazaar-go` running. I get an error with `go get`.

```
Justins-MacBook-Air:ob-go justin$ go get -u github.com/OpenBazaar/openbazaar-go
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x53b3c0, 0xc820010090)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.vendoredImportPath(0xc821127000, 0xc821151fc1, 0x1e, 0x0, 0x0)
	/usr/local/go/src/cmd/go/pkg.go:466 +0x713
main.loadImport(0xc821151fc1, 0x1e, 0xc8208d3180, 0x7d, 0xc821127000, 0xc8208c3788, 0xc82114f470, 0x1, 0x1, 0x1, ...)
	/usr/local/go/src/cmd/go/pkg.go:336 +0xe52
main.(*Package).load(0xc821127000, 0xc8208c3788, 0xc82104a700, 0x0, 0x0, 0x4)
	/usr/local/go/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0xc820fe8b11, 0x29, 0xc820ff6190, 0x4c, 0xc820ff3800, 0xc8208c3788, 0xc820fe9770, 0x1, 0x1, 0x1, ...)
	/usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.(*Package).load(0xc820ff3800, 0xc8208c3788, 0xc820e61180, 0x0, 0x0, 0xc)
	/usr/local/go/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0x7fff5fbffbc2, 0x23, 0xc820014064, 0x24, 0x0, 0xc8208c3788, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.loadPackage(0x7fff5fbffbc2, 0x23, 0xc8208c3788, 0x0)
	/usr/local/go/src/cmd/go/pkg.go:1639 +0x13d8
main.packagesAndErrors(0xc820aa7930, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/go/pkg.go:1684 +0x531
main.packagesForBuild(0xc820aa7910, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/go/pkg.go:1700 +0x82
main.runGet(0x885fe0, 0xc820aa7910, 0x1, 0x1)
	/usr/local/go/src/cmd/go/get.go:131 +0x3f2
main.main()
	/usr/local/go/src/cmd/go/main.go:181 +0x783
```

**Comment by hoffmabc** [comment]
This bug was fixed I believe @cpacia ?

**Comment by cpacia** [comment]
I'm not seeing it. I would close it. I think it was just a problem with his system. Maybe related to the repo bug.
