### ISSUE TITLE
Panic: interface conversion

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#49]
I've started from scratch, following instructions [here](https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/install-osx.md). A few seconds after running I get a panic.

```
Justins-MacBook-Air:ob-go justin$ go get github.com/OpenBazaar/openbazaar-go
Justins-MacBook-Air:ob-go justin$ cd $GOPATH/src/github.com/OpenBazaar/openbazaar-go
Justins-MacBook-Air:openbazaar-go justin$ go run openbazaard.go start
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v2.0 starting...
17:36:11.677 [Execute] [INFO] Peer ID:  QmcQSSjQZi2bHGbR3e7xU9UYEjKwAiWoGbzVdbXftnTjsy
17:36:11.681 [printSwarmAddrs] [INFO] Swarm listening on /ip4/127.0.0.1/tcp/4001
17:36:11.681 [printSwarmAddrs] [INFO] Swarm listening on /ip4/127.0.0.1/udp/4001/utp
17:36:11.681 [printSwarmAddrs] [INFO] Swarm listening on /ip4/192.168.0.16/tcp/4001
17:36:11.681 [printSwarmAddrs] [INFO] Swarm listening on /ip4/192.168.0.16/udp/4001/utp
17:36:11.681 [printSwarmAddrs] [INFO] Swarm listening on /ip4/78.221.67.24/tcp/4001
17:36:11.681 [printSwarmAddrs] [INFO] Swarm listening on /ip6/::1/tcp/4001
17:36:11.681 [printSwarmAddrs] [INFO] Swarm listening on /ip6/::1/udp/4001/utp
17:36:11.697 [Execute] [INFO] Starting bitcoin wallet...
17:36:11.698 [fetchCurrentRates] [INFO] Fetching bitcoin exchange rates
17:36:11.698 [serveHTTPGateway] [INFO] Gateway/API server listening on /ip4/127.0.0.1/tcp/8080
panic: interface conversion: interface is nil, not string

goroutine 228 [running]:
panic(0x4ddc8a0, 0xc822485f00)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/OpenBazaar/openbazaar-go/repo.GetAPIUsernameAndPw(0xc8224a0ea0, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/justin/Desktop/duomoney/ob-go/src/github.com/OpenBazaar/openbazaar-go/repo/config.go:28 +0x25c
github.com/OpenBazaar/openbazaar-go/api.newRestAPIHandler(0xc822181260, 0x0, 0x0, 0x0, 0xc8224a0a80, 0x0, 0x0)
	/Users/justin/Desktop/duomoney/ob-go/src/github.com/OpenBazaar/openbazaar-go/api/restapi.go:51 +0x325
github.com/OpenBazaar/openbazaar-go/api.makeHandler(0xc822181260, 0xc820419a01, 0xc820159ea0, 0x1b, 0x0, 0xc822494700, 0xc8223fef40, 0x0, 0xc822479030, 0x6b4b490, ...)
	/Users/justin/Desktop/duomoney/ob-go/src/github.com/OpenBazaar/openbazaar-go/api/gateway.go:21 +0x111
github.com/OpenBazaar/openbazaar-go/api.Serve(0xc822496900, 0xc822181260, 0x4d62701, 0xc820159ea0, 0x1b, 0x0, 0xc822494700, 0xc8223fef40, 0x0, 0xc822479030, ...)
	/Users/justin/Desktop/duomoney/ob-go/src/github.com/OpenBazaar/openbazaar-go/api/gateway.go:47 +0xed
main.serveHTTPGateway.func1(0xc8224968a0, 0xc822496900, 0xc822181260, 0x680ccf0, 0xc8224917a0, 0xc8224a0a50, 0x5, 0x5)
	/Users/justin/Desktop/duomoney/ob-go/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go:451 +0xb6
created by main.serveHTTPGateway
	/Users/justin/Desktop/duomoney/ob-go/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go:453 +0xa24
exit status 2
```

**Comment by cpacia** [comment]
Delete the .openbazaar2.0 folder and try again. There are likely to be a number of database and repo changes in the next few weeks that will require changes.

**Comment by JustinDrake** [comment]
@cpacia Where is the `openbazaar2.0` folder? In `~/Library/Application Support` I can only see `OpenBazaar`.

**Comment by JustinDrake** [comment]
Ok, found the folder (it's `~/OpenBazaar2.0`). @cpacia, can we please put it in the appropriate location for Mac (namely `~/Library/Application Support`).

**Comment by cpacia** [comment]
Feel free to submit a PR. I don't have a mac to test it.

**Comment by hoffmabc** [comment]
I'll open a different issue for this action.
