### ISSUE TITLE
panic killing openbazaar-go daemon

### ISSUE THREAD

**Issue by whyrusleeping** [OpenBazaar/openbazaar-go#506]
Killed the `openbazaar-go start` command with a ctrl-c and it gave me a panic:
```
^C15:55:16.767 [func1] [NOTICE] Received interrupt
15:55:16.767 [func1] [INFO] OpenBazaar Server shutting down...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe1b4aa]

goroutine 5373 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/whyrusleeping/go/src/database/sql/sql.go:2422 +0x7a
database/sql.(*Rows).Close(0x0, 0x0, 0x0)
        /home/whyrusleeping/go/src/database/sql/sql.go:2418 +0x3d
github.com/OpenBazaar/openbazaar-go/repo/db.(*TxnsDB).GetAll(0xc42040f760, 0x1c74901, 0x0, 0x0, 0x0, 0x1c60e20, 0xc420012e10)
        /home/whyrusleeping/gopkg/src/github.com/OpenBazaar/openbazaar-go/repo/db/txns.go:89 +0x85b
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*TxStore).CheckDoubleSpends(0xc420a23500, 0xc421b5fe40, 0x0, 0xc42174d6d8, 0xc09580, 0xc42006c0c0, 0xc4210a0130)
        /home/whyrusleeping/gopkg/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/txstore.go:120 +0xc1
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*TxStore).Ingest(0xc420a23500, 0xc421b5fe40, 0xc40006c5f2, 0xc42077d508, 0xe26c2b9f8cbfc533, 0xc42001c0e0)
        /home/whyrusleeping/gopkg/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/txstore.go:219 +0xe5
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).onTx(0xc420a1abb0, 0xc420991b80, 0xc421b5fe40)
        /home/whyrusleeping/gopkg/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/eight333.go:120 +0x101
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).(github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.onTx)-fm(0xc420991b80, 0xc421b5fe40)
        /home/whyrusleeping/gopkg/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/wallet.go:100 +0x3e
github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer.(*Peer).inHandler(0xc420991b80)
        /home/whyrusleeping/gopkg/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer/peer.go:1504 +0x124f
created by github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer.(*Peer).start
        /home/whyrusleeping/gopkg/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/btcsuite/btcd/peer/peer.go:1965 +0x2b6
```

**Comment by cpacia** [comment]
I think you killed it before the wallet fired up. I need to handle that case better.

**Comment by cpacia** [comment]
Maybe it could also be a previous data directory on your system? I haven't done any migrations yet.

**Comment by whyrusleeping** [comment]
I probably killed it before the wallet fired up, yeah. This is the first
time using openbazaar on this laptop

**Comment by cpacia** [comment]
Should be fixed.
