### ISSUE TITLE
the closedispute api triggers a panic

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#558]
```
13:47:13.276 [func1] [ERROR] A panic occurred in the rest api handler!
13:47:13.276 [func1] [ERROR] runtime error: integer divide by zero
goroutine 408 [running]:
runtime/debug.Stack(0x4301dab, 0xc4202c0990, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:152 +0x150
panic(0x4cf3e80, 0xc4200120b0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).CreateMultisigSignature(0xc420856900, 0xc421a78c80, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc4226982d0, 0xc422a0eaf0, 0x69, ...)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go:223 +0x916
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).CloseDispute(0xc42093e240, 0xc42281e330, 0x2e, 0x42c80000, 0xc422a10200, 0x16, 0x11, 0x11)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/core/disputes.go:609 +0x116f
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTCloseDispute(0xc42087cf00, 0x5658200, 0xc421f141a0, 0xc420fada40)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:1954 +0x182
github.com/OpenBazaar/openbazaar-go/api.post(0xc42087cf00, 0xc422a101a0, 0x11, 0x5658200, 0xc421f141a0, 0xc420fada40)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:62 +0x8fe
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc42087cf00, 0x5658200, 0xc421f141a0, 0xc420fada40)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:161 +0x93f
net/http.(*ServeMux).ServeHTTP(0xc420937440, 0x5658200, 0xc421f141a0, 0xc420fada40)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420913080, 0x5658200, 0xc421f141a0, 0xc420fada40)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc421172100, 0x5659280, 0xc420aa2040)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

This is possibly due to not properly handling low priced listings.

**Comment by cpacia** [comment]
Fixed
