### ISSUE TITLE
the releasefunds api triggers a panic when the amounts are too low

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#559]
```
16:44:14.425 [func1] [ERROR] A panic occurred in the rest api handler!
16:44:14.425 [func1] [ERROR] runtime error: integer divide by zero
goroutine 73142 [running]:
runtime/debug.Stack(0x430344b, 0xc4202f40f0, 0x1)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
    /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
    /Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:152 +0x150
panic(0x4cf5680, 0xc4200100b0)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet.(*SPVWallet).Multisign(0xc4208e73b0, 0xc423313840, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc42025cee0, 0x1, 0x1, ...)
    /Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go:268 +0xb4e
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).ReleaseFunds(0xc4208405a0, 0xc42281e500, 0xc4212f1560, 0x1, 0x4, 0xc4212f1560, 0x1)
    /Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/core/disputes.go:1091 +0xb6a
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTReleaseFunds(0xc4200a8d20, 0x565a1c0, 0xc420f5d5f0, 0xc4217403c0)
    /Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:2042 +0x27f
github.com/OpenBazaar/openbazaar-go/api.post(0xc4200a8d20, 0xc4212636e0, 0x10, 0x565a1c0, 0xc420f5d5f0, 0xc4217403c0)
    /Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:64 +0x892
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc4200a8d20, 0x565a1c0, 0xc420f5d5f0, 0xc4217403c0)
    /Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:161 +0x93f
net/http.(*ServeMux).ServeHTTP(0xc420909ec0, 0x565a1c0, 0xc420f5d5f0, 0xc4217403c0)
    /usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc4208fc400, 0x565a1c0, 0xc420f5d5f0, 0xc4217403c0)
    /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc423e39200, 0x565b240, 0xc42368b080)
    /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by cpacia** [comment]
May be fixed. Need to validate.
