### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mariodian** [OpenBazaar/openbazaar-go#593]
Hey,

I haven't been running my server for around a week. Today, I updated the repo (as well as the desktop app), started the server and was asked to create a new OB ID. 

@cpacia helped me to restore my ID with my mnemonic seed, but when I started the server again it crashed with this error:

```
23:44:44.003 [SendMessage] [DEBUG] Sending OFFLINE_ACK message to QmZSNTZF4pBaX2gyn2ihFNrSyjgVcvYEPRyNwNU5ZqCZoT
23:44:44.006 [SendOfflineMessage] [DEBUG] Sending offline message to QmZSNTZF4pBaX2gyn2ihFNrSyjgVcvYEPRyNwNU5ZqCZoT
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc98b46]

goroutine 357 [running]:
github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes.AnyMessageName(0x0, 0x116d560, 0xc42197bbf0, 0x2, 0x38)
	/home/satoshi/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes/any.go:54 +0x26
github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes.UnmarshalAny(0x0, 0x1ca99e0, 0xc421bfb4f0, 0xc421a9e160, 0x10)
	/home/satoshi/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes/any.go:116 +0x161
github.com/OpenBazaar/openbazaar-go/net/service.(*OpenBazaarService).handleModeratorAdd(0xc4201e2bb0, 0xc42197bc20, 0x22, 0xc420762fa0, 0x105fa20, 0xc421a9e170, 0xc421a9e170, 0xc420f939d7, 0xc421a9e170)
	/home/satoshi/go/src/github.com/OpenBazaar/openbazaar-go/net/service/handlers.go:1115 +0x72
github.com/OpenBazaar/openbazaar-go/net/service.(*OpenBazaarService).(github.com/OpenBazaar/openbazaar-go/net/service.handleModeratorAdd)-fm(0xc42197bc20, 0x22, 0xc420762fa0, 0x105fa20, 0xc421a9e170, 0x0, 0x0, 0xc420f93a88)
	/home/satoshi/go/src/github.com/OpenBazaar/openbazaar-go/net/service/handlers.go:60 +0x5c
github.com/OpenBazaar/openbazaar-go/net/retriever.(*MessageRetriever).handleMessage(0xc42071ed80, 0xc420762fa0, 0xc421948e40, 0x24, 0x24, 0xc4219b4d40, 0x40, 0x40, 0xc420f93a10, 0x0, ...)
	/home/satoshi/go/src/github.com/OpenBazaar/openbazaar-go/net/retriever/retriever.go:391 +0x104
github.com/OpenBazaar/openbazaar-go/net/retriever.(*MessageRetriever).queueMessage(0xc42071ed80, 0xc420762fa0, 0xc421948e40, 0x24, 0x24, 0xc4219b4d40, 0x40, 0x40, 0xc421bbe2c0, 0x34)
	/home/satoshi/go/src/github.com/OpenBazaar/openbazaar-go/net/retriever/retriever.go:293 +0xef
github.com/OpenBazaar/openbazaar-go/net/retriever.(*MessageRetriever).attemptDecrypt(0xc42071ed80, 0xc42097be00, 0xb4, 0xb4, 0xc4201d8450, 0x22, 0x1cb3d40, 0xc4201c8520)
	/home/satoshi/go/src/github.com/OpenBazaar/openbazaar-go/net/retriever/retriever.go:264 +0x3b7
github.com/OpenBazaar/openbazaar-go/net/retriever.(*MessageRetriever).fetchIPFS(0xc42071ed80, 0xc4201d8450, 0x22, 0x1, 0xc42049f020, 0x1c, 0x0, 0x0, 0xc42083c640, 0x0, ...)
	/home/satoshi/go/src/github.com/OpenBazaar/openbazaar-go/net/retriever/retriever.go:198 +0x2b7
created by github.com/OpenBazaar/openbazaar-go/net/retriever.(*MessageRetriever).fetchPointers
	/home/satoshi/go/src/github.com/OpenBazaar/openbazaar-go/net/retriever/retriever.go:114 +0x6fe
exit status 2
```

When I started the server again, it worked fine. I still think it's worth having a look at it. I was able to reproduce this error every time.

Steps:

1) remove .openbazaar2.0 data folder
2) restore your ID with `go run $GOPATH/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go init -m "your mnemonic seed"`
3) set up API "username" and "password": `go run $GOPATH/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go setapicreds`
4) edit config file according to your needs (change the listening IP, turn on SSL etc)
5) start the server `go run $GOPATH/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go start`
(crashes with the above error)
6) repeat step 5 with success

My specs:
Ubuntu 17.04, Intel NUC 7i3 with 16GB RAM
go version go1.8.3 linux/amd64

**Comment by cpacia** [comment]
So it downloaded an offline message from the network and then panic with a nil pointer when attempting to parse it. 

I'll have to take a deeper look at why that happened.

**Comment by cpacia** [comment]
So this was due to a change in payload format on that message from version 0.6.x to 0.7.0. Thankfully it was caught now.
