### ISSUE TITLE
Server crashed when selecting moderator for store

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/openbazaar-go#670]
When I went into setting and clicked on "Choose Moderator" the server crashed. I can upload the whole log if needed but here's a selection of the terminal output.

```
github.com/OpenBazaar/openbazaar-go/vendor/github.com/ipfs/go-ipfs/exchange/bitswap/network.(*impl).handleNewStream(0xc4204a1ec0, 0x1ca4ac0, 0xc423864f40)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/ipfs/go-ipfs/exchange/bitswap/network/ipfs_impl.go:188 +0x21c
github.com/OpenBazaar/openbazaar-go/vendor/github.com/ipfs/go-ipfs/exchange/bitswap/network.(*impl).(github.com/OpenBazaar/openbazaar-go/vendor/github.com/ipfs/go-ipfs/exchange/bitswap/network.handleNewStream)-fm(0x1ca4ac0, 0xc423864f40)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/ipfs/go-ipfs/exchange/bitswap/network/ipfs_impl.go:32 +0x3e
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmQA5mdxru8Bh6dpC9PJfSkumqnmHgJX7knxSgBo5Lpime/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc423d7c9a0, 0x19, 0x7f5af84222e8, 0xc423864f40, 0x4a6f111, 0xc4206f48c0)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmQA5mdxru8Bh6dpC9PJfSkumqnmHgJX7knxSgBo5Lpime/go-libp2p/p2p/host/basic/basic_host.go:188 +0xb9
created by github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmQA5mdxru8Bh6dpC9PJfSkumqnmHgJX7knxSgBo5Lpime/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmQA5mdxru8Bh6dpC9PJfSkumqnmHgJX7knxSgBo5Lpime/go-libp2p/p2p/host/basic/basic_host.go:152 +0x854

goroutine 528419 [chan receive, 196 minutes]:
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport.(*listener).handleWsConn(0xc4205de4e0, 0xc424b382d0)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport/websocket.go:198 +0x111
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport.(*listener).(github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport.handleWsConn)-fm(0xc424b382d0)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport/websocket.go:171 +0x34
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket.Server.serveWebSocket(0x0, 0xc420156f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket/server.go:89 +0x1cd
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket.Server.ServeHTTP(0x0, 0xc420156f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket/server.go:70 +0x75
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket.(*Server).ServeHTTP(0xc4205a4d20, 0x1c9c340, 0xc423a81d40, 0xc423e23860)
	<autogenerated>:88 +0x9e
net/http.serverHandler.ServeHTTP(0xc4205cc080, 0x1c9c340, 0xc423a81d40, 0xc423e23860)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42394f200, 0x1c9d440, 0xc422ac8040)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

goroutine 814026 [select]:
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux.(*Session).AcceptStream(0xc4249408f0, 0xc425f86f78, 0xc425f86f68, 0xaf79af)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux/session.go:201 +0x1bb
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/Qmbn7RYyWzBVXiUp9jZ1dA4VADHy9DtS7iZLwfhEUQvm3U/go-smux-yamux.(*conn).AcceptStream(0xc4249408f0, 0xc4279d5340, 0x1ca2cc0, 0xc4229445b0, 0x0)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/Qmbn7RYyWzBVXiUp9jZ1dA4VADHy9DtS7iZLwfhEUQvm3U/go-smux-yamux/yamux.go:71 +0x2b
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/Qmbn7RYyWzBVXiUp9jZ1dA4VADHy9DtS7iZLwfhEUQvm3U/go-smux-yamux.(*conn).Serve(0xc4249408f0, 0xc4279d5340)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/Qmbn7RYyWzBVXiUp9jZ1dA4VADHy9DtS7iZLwfhEUQvm3U/go-smux-yamux/yamux.go:79 +0x2b
created by github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmYBtUjY2Q3jY8eYAva99G44zefLZ5Ksgk66VG81ueKQp1/go-peerstream.(*Swarm).addConn
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmYBtUjY2Q3jY8eYAva99G44zefLZ5Ksgk66VG81ueKQp1/go-peerstream/conn.go:214 +0x1b1

goroutine 528502 [chan receive, 196 minutes]:
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport.(*listener).handleWsConn(0xc4205de4e0, 0xc424b5abd0)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport/websocket.go:198 +0x111
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport.(*listener).(github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport.handleWsConn)-fm(0xc424b5abd0)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmbAnytXbEyaVaiwkA2xPp8PPnkFKnQcfBMdXAcSfnjKtB/ws-transport/websocket.go:171 +0x34
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket.Server.serveWebSocket(0x0, 0xc420156f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket/server.go:89 +0x1cd
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket.Server.ServeHTTP(0x0, 0xc420156f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/nondescript/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket/server.go:70 +0x75
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmTDQRD9abCLfdZCjVxuujSVq1X7pkW8eXhaJtgsjH2fnT/websocket.(*Server).ServeHTTP(0xc4205a4d20, 0x1c9c340, 0xc423430a90, 0xc422c960f0)
	<autogenerated>:88 +0x9e
net/http.serverHandler.ServeHTTP(0xc4205cc080, 0x1c9c340, 0xc423430a90, 0xc422c960f0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4237fd100, 0x1c9d440, 0xc4234f66c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

goroutine 920998 [select]:
net/http.setRequestCancel.func4(0x0, 0xc42941c570, 0xc427d99640, 0xc425168660)
	/usr/local/go/src/net/http/client.go:329 +0x15a
created by net/http.setRequestCancel
	/usr/local/go/src/net/http/client.go:337 +0x29f
```

**Comment by cpacia** [comment]
Log doesn't help. If someone else sees this let's try to figure out how to reproduce it.

**Comment by SamPatt** [comment]
Replicated in #682

**Comment by jjeffryes** [comment]
I called http://localhost:4202/ob/moderators?async=true&include=profile

The server closed with exit status 2

This was at the end of the ob.log

[Resolve] [ERROR] Could not resolve name.
17:21:12.721 [Resolve] [ERROR] Could not resolve name.
