### ISSUE TITLE
The close dispute api panics if awarding funds to a party who's contract has validation errors

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#861]
1. Make a moderated purchase.
2. Modify the vendors contract on disk.
3. Have the vendor open a dispute.
4. As the mod, attempt to close the dispute awarding some funds to the vendor.

Observed:

```
```
runtime/debug.Stack(0x483fc5b, 0xc42016c2d0, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:166 +0x119
panic(0x4e3db00, 0x5b09940)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/bchutil.DecodeAddress(0x0, 0x0, 0xc4205c8780, 0x0, 0x0, 0x5a21180, 0xc420a56620)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/bchutil/cashaddr.go:385 +0x781
github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/BitcoinCash-Wallet.(*SPVWallet).DecodeAddress(0xc4205ae0b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/BitcoinCash-Wallet/wallet.go:238 +0x83
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).CloseDispute(0xc4205c8b40, 0xc4237bf290, 0x2e, 0x4248000042480000, 0xc42478aa90, 0xf, 0xc423edb6c0, 0xc423c3ce28)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/core/disputes.go:527 +0x2576
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTCloseDispute(0xc4205f0690, 0x5a31900, 0xc4275fa1c0, 0xc42064d400)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:2057 +0x13e
github.com/OpenBazaar/openbazaar-go/api.post(0xc4205f0690, 0xc423edb6c0, 0x11, 0x5a31900, 0xc4275fa1c0, 0xc42064d400)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:64 +0xc7e
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc4205f0690, 0x5a31900, 0xc4275fa1c0, 0xc42064d400)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:175 +0x880
net/http.(*ServeMux).ServeHTTP(0xc420703380, 0x5a31900, 0xc4275fa1c0, 0xc42064d400)
	/usr/local/go/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc4202b7930, 0x5a31900, 0xc4275fa1c0, 0xc42064d400)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc422ed7c20, 0x5a32b00, 0xc428234bc0)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
goroutine 348254 [running]:
runtime/debug.Stack(0x483fc5b, 0xc42016c2d0, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:166 +0x119
panic(0x4e3db00, 0x5b09940)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/bchutil.DecodeAddress(0x0, 0x0, 0xc4205c8780, 0x0, 0x0, 0x5a21180, 0xc421f2cb00)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/bchutil/cashaddr.go:385 +0x781
github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/BitcoinCash-Wallet.(*SPVWallet).DecodeAddress(0xc4205ae0b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/cpacia/BitcoinCash-Wallet/wallet.go:238 +0x83
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).CloseDispute(0xc4205c8b40, 0xc423039200, 0x2e, 0x42c80000, 0xc424d97d20, 0xf, 0xc422bf2e80, 0xc425306a38)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/core/disputes.go:527 +0x2576
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTCloseDispute(0xc4205f0690, 0x5a31900, 0xc4201787e0, 0xc427782000)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:2057 +0x13e
github.com/OpenBazaar/openbazaar-go/api.post(0xc4205f0690, 0xc422bf2e80, 0x11, 0x5a31900, 0xc4201787e0, 0xc427782000)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:64 +0xc7e
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc4205f0690, 0x5a31900, 0xc4201787e0, 0xc427782000)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:175 +0x880
net/http.(*ServeMux).ServeHTTP(0xc420703380, 0x5a31900, 0xc4201787e0, 0xc427782000)
	/usr/local/go/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc4202b7930, 0x5a31900, 0xc4201787e0, 0xc427782000)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc422ed7c20, 0x5a32b00, 0xc428234bc0)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```

Expected:

No panic and the dispute is resolved.

**Comment by rmisio** [comment]
Here's the case payload the moderator got:

```
{
    "timestamp": "2018-02-09T22:42:28.000Z",
    "vendorContract": {
        "vendorListings": [
            {
                "slug": "filly-feel-good-pooper",
                "vendorID": {
                    "peerID": "QmTmUABEjJeN3j2nweK8Ejgs5tVkMLP46XDLxm1EKEP6e3",
                    "handle": "",
                    "pubkeys": {
                        "identity": "CAESIA20FS20GNAK3d2akcwFKi0j2u2LY9tT9JDUK5YJx0L3",
                        "bitcoin": "Asfkm4AhsNeBmrS1+cNZBZNAE3OY43yn2Jy2MCzdSTSB"
                    },
                    "bitcoinSig": "MEQCIAGPchZIhwcuTNzndibNmGFBkL6MPfAWfoE2Bs23LmTpAiBxJeIbOXr+yjVVvYgDe9V81FLUdsYDaLgKKZgHqvRT4Q=="
                },
                "metadata": {
                    "version": 2,
                    "contractType": "DIGITAL_GOOD",
                    "format": "FIXED_PRICE",
                    "expiry": "2037-12-31T08:00:00.000Z",
                    "acceptedCurrencies": [
                        "TBCH"
                    ],
                    "pricingCurrency": "USD",
                    "language": "",
                    "escrowTimeoutHours": 1
                },
                "item": {
                    "title": "filly feel good",
                    "description": "",
                    "processingTime": "",
                    "price": 100,
                    "nsfw": false,
                    "images": [
                        {
                            "filename": "River-HD-Wallpapers.jpg",
                            "original": "zdj7WatcMJyxZTzDUwE7nMd5mYM5ozvdVTp7Hf4XjU366gEbg",
                            "large": "zdj7WWRiBScpwdaUmNgsmdgrF9xDX7KNzp7ApPcj2xXkGA13U",
                            "medium": "zb2rhcJvWB5zhQb5bhJRcuxYjy2jkz7PgJu2WJfFF8a6simTf",
                            "small": "zb2rhX9dB3XnzMXcbTkzCHVerz1g1tTDu8veMTod3gKBv98RB",
                            "tiny": "zb2rhedegZXnGsbXLjB3WgKa6M2SquEdcxZ9jKXX7CBvw6BTB"
                        }
                    ],
                    "grams": 0,
                    "condition": "NEW",
                    "skus": [
                        {
                            "productID": "",
                            "surcharge": 0,
                            "quantity": 0
                        }
                    ]
                },
                "moderators": [
                    "QmSdHi9bGY69511SdpUQFvNqC65oJ24r8GymbY5oywhdgk"
                ],
                "termsAndConditions": "",
                "refundPolicy": ""
            }
        ],
        "buyerOrder": {
            "refundAddress": "bchtest:qzv2tcan7en6j7dd4dv9n3j4pemj5na89q6j69zatm",
            "refundFee": 17,
            "shipping": {
                "shipTo": "",
                "address": "",
                "city": "",
                "state": "",
                "postalCode": "",
                "country": "NA",
                "addressNotes": ""
            },
            "buyerID": {
                "peerID": "QmNrg5mZSdsfJcS2s4p8fEmJFUwfLRjhMUcpvY6hEALC4n",
                "handle": "",
                "pubkeys": {
                    "identity": "CAESIG3i3aehcpKGDOhg6oMzNz79LfJj8kf1r0mseblgb2lq",
                    "bitcoin": "AipQhuDMDw3KLf3GHo13yy9qHMb3LYqsI7y99KyJFV25"
                },
                "bitcoinSig": "MEUCIQDBXnVL4r8CwaEEHEWl6rb3OHX/iHg4tECzMsHPmKbiIAIgF86vDoYryig/QcVeaSEprpRSx82HkxSRTqo8C4VmE8o="
            },
            "timestamp": "2018-02-09T21:52:26.116101Z",
            "items": [
                {
                    "listingHash": "zb2rhcmcoa2tV2snR1KFmkGcq12K3AwxvRJxqhKxxK4kBC4u4",
                    "quantity": 1,
                    "shippingOption": {
                        "name": "",
                        "service": ""
                    },
                    "memo": ""
                }
            ],
            "payment": {
                "method": "MODERATED",
                "moderator": "QmSdHi9bGY69511SdpUQFvNqC65oJ24r8GymbY5oywhdgk",
                "amount": 78631,
                "chaincode": "c753c2da476eee8db5bc2e9e0843c1dbede23b9b84fba555537cda4feeb84228",
                "address": "bchtest:prm5mkmcw3z8lr4rrkffcchrp7kppya7sgqandae7s",
                "redeemScript": "63522103d8b6c89d627af5f7ae60862612ac5356caa0de9bb7d7ae709ca0fd7552d1d1232103b201e813feb31f554006b52203bc188266fa67927b42035bf75ee79be319c3ad21022f514455d8c33d4653660ee35435a6b257e50534786d8fc4437df50858a4e30d53ae6756b2752103b201e813feb31f554006b52203bc188266fa67927b42035bf75ee79be319c3adac68",
                "moderatorKey": "Ai9RRFXYwz1GU2YO41Q1prJX5QU0eG2PxEN99QhYpOMN"
            },
            "ratingKeys": [
                "A15FfwEBDYDtQexLqQe5d+w0ppgfg2GS6ZVNgjoDddY+"
            ],
            "alternateContactInfo": "",
            "version": 1
        },
        "vendorOrderConfirmation": {
            "orderID": "Qme4ka5rv1JSs94twtJhgpHvNspnXZuanCCd6bktYpkECV",
            "timestamp": "2018-02-09T21:52:38.056959Z",
            "paymentAddress": "bchtest:prm5mkmcw3z8lr4rrkffcchrp7kppya7sgqandae7s",
            "requestedAmount": 78631,
            "ratingSignatures": [
                {
                    "metadata": {
                        "listingSlug": "filly-feel-good",
                        "moderatorKey": "Ai9RRFXYwz1GU2YO41Q1prJX5QU0eG2PxEN99QhYpOMN",
                        "listingTitle": "filly feel good",
                        "thumbnail": {
                            "tiny": "zb2rhedegZXnGsbXLjB3WgKa6M2SquEdcxZ9jKXX7CBvw6BTB",
                            "small": "zb2rhX9dB3XnzMXcbTkzCHVerz1g1tTDu8veMTod3gKBv98RB",
                            "medium": "zb2rhcJvWB5zhQb5bhJRcuxYjy2jkz7PgJu2WJfFF8a6simTf",
                            "large": "zdj7WWRiBScpwdaUmNgsmdgrF9xDX7KNzp7ApPcj2xXkGA13U",
                            "original": "zdj7WatcMJyxZTzDUwE7nMd5mYM5ozvdVTp7Hf4XjU366gEbg"
                        }
                    },
                    "signature": "5nGKM5+W4HYKryr4JyLzm7CtkRE7NeJp1gR22rL/uH3vQAH6ZhmVdmq2Upz8z1H+Sik3oxqPOb7lG+/I1x21DQ=="
                }
            ]
        },
        "signatures": [
            {
                "section": "LISTING",
                "signatureBytes": "1BWU3H5wMYlYkeKi0KGekY6WsH/ValY0Apw8vLln5imOC88/jOxka+s4uHkbvtKHzyliKIeqs8cPhdvZ7RGGBw=="
            },
            {
                "section": "ORDER",
                "signatureBytes": "8dzmp0zx31E2L2DtHnDQloCAYzylcChTPTHa47tiWTK7qcHWsd/DMoLOQU8UKxEhUq47z/X+KnJHUI/sOsHcAw=="
            },
            {
                "section": "ORDER_CONFIRMATION",
                "signatureBytes": "jCQGiaBSM5AyoUv5S+79OYX5eLAwdROomiooRBD4DTTtS7b9/vXGvYB7Aqa3z4APzxWOtAXvgn7flzdrSMdRCw=="
            }
        ]
    },
    "vendorContractValidationErrors": [
        "Not all items in the order have a matching vendor listing",
        "Invalid vendor signature on listing 0Invalid signature"
    ],
    "state": "DISPUTED",
    "read": true,
    "buyerOpened": false,
    "claim": "please work",
    "unreadChatMessages": 0
}
```
